import type { Metadata } from 'next';
import { Fira_Code, Montserrat } from 'next/font/google';
// @ts-expect-error ignore
import './globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import SessionProvider from '../components/molecules/providers/session-provider';
import { Toaster } from '@/components/atoms/sonner';
import { ScrollToTop } from '@/components/molecules/scrolls';

const montserrat = Montserrat({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
});

const firaCode = Fira_Code({
  variable: '--font-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${firaCode.variable} overflow-x-hidden antialiased`}
      >
        <SessionProvider session={session}>
          <ScrollToTop />
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
